### ISSUE TITLE
maximumPreviewWidth affecting captured (non-preview) image size?

### ISSUE THREAD

**Issue by red42** [siralam/CameraViewPlus#16]
My CameraView is setup as follows:

```
    <com.google.android.cameraview.CameraView
        android:id="@+id/camera_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:keepScreenOn="true"
        android:adjustViewBounds="true"
        app:autoFocus="true"
        app:cameraAspectRatio="4:3"
        app:facing="back"
        app:flash="off"
        app:maximumWidth="4000"
        app:maximumPreviewWidth="1200"
        app:useHighResPicture="false"/>
```
This works fine, and the width received on my OnPictureTakenListener.onPictureTaken is 2592.

I changed the maximumPreviewWidth to 240 in order to perform some heavy-ish image processing on my OnFrameListener, but then the captured image (at onPictureTaken, not frame preview) reports a width of 352.

Is this the expected result? I was assuming maximumPreviewWidth only affected the live preview and at most the frames on OnFrameListener.

Setting app:useHighResPicture to true has no effect, I keep capturing low-res images.

**Comment by siralam** [comment]
Hmm This is not expected. Let me check when I have time.
Thanks for reporting!

**Comment by siralam** [comment]
@red42 Hello, I tried today but cannot reproduce the issue. Are you still experiencing?
