### ISSUE TITLE
Zoom on pitch isn't opcional

### ISSUE THREAD

**Issue by oscarcpozas** [siralam/CameraViewPlus#5]
I'm trying implement your project but I don't see the option to disable the zoom. It's possible?

**Comment by siralam** [comment]
Oh you are right I didn't make it optional. Will add that in the future. For now, you may try

cameraView.setPixelsPerOneZoomLevel(Integer.MAX_VALUE)

**Comment by oscarcpozas** [comment]
If you assign it to me, I'll make a pull request with the necessary changes.

**Comment by siralam** [comment]
@oscarcpozas You are welcomed, just feel free to do that :)

**Comment by oscarcpozas** [comment]
It's here: https://github.com/siralam/CameraViewPlus/pull/7
